# GitOps values for notebook-controller.

# Labels to add to all resources
commonLabels:
  app: notebook-controller

image:
  repository: us-central1-docker.pkg.dev/teknoir-mgmt/controllers/notebook-controller
  tag: 20260330-084828
  pullPolicy: Always

imagePullSecrets:
  - name: gcr-json-key

serviceAccount:
  name: notebook-controller-service-account

addFsGroup: "true"

parameters:
  USE_ISTIO: "true"
  ISTIO_GATEWAY: istio-system/teknoir-gateway
  POD_LABELS: gcp-cred-secret=user-gcp-sa,gcp-cred-secret-filename=user-gcp-sa.json
  project-id: teknoir
  domain: teknoir.cloud
