---
apiVersion: v1
kind: ConfigMap
metadata:
  name: deadend-stunnel-config
  namespace: teknoir-demo
data:
  stunnel.conf: |
    foreground = yes
    [ssh-tls]
    accept = 0.0.0.0:2222
    connect = 127.0.0.1:22
    cert = /etc/stunnel/certs/tls.crt
    key = /etc/stunnel/certs/tls.key