---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    teknoir.org/plugin: deadend
    app: deadend
  name: deadend
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deadend
  template:
    metadata:
      labels:
        teknoir.org/plugin: deadend
        app: deadend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: deadend
        image: "ghcr.io/teknoir/deadend:{{ .Values.imageTag }}"
        imagePullPolicy: Always
        ports:
          - containerPort: 22
            name: tcp-ssh
            protocol: TCP
        volumeMounts:
          - name: deadend-authorized-keys
            mountPath: /secret-keys
      - name: tls-terminator
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            apk add --no-cache stunnel
            stunnel /etc/stunnel/stunnel.conf
        ports:
          - containerPort: 2222
        volumeMounts:
          - name: certs
            mountPath: /etc/stunnel/certs
            readOnly: true
          - name: stunnel-config
            mountPath: /etc/stunnel/stunnel.conf
            subPath: stunnel.conf
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 25m
            memory: 20Mi
      volumes:
        - name: deadend-authorized-keys
          secret:
            secretName: deadend-authorized-keys-secret
            defaultMode: 0644
        - name: certs
          secret:
            secretName: domain-wildcard-tls
        - name: stunnel-config
          configMap:
            name: deadend-stunnel-config
      serviceAccountName: deadend-service-account

