---
apiVersion: v1
kind: Service
metadata:
  labels:
    teknoir.org/plugin: deadend
  name: deadend
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: deadend
  ports:
    - name: tls-ssh
      port: 2222
      targetPort: 2222
