---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    teknoir.org/plugin: deadend
  name: deadend
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - 'deadend-{{ .Release.Namespace }}.{{ .Values.domain }}'
  gateways:
    - istio-system/teknoir-gateway-public
  tcp:
    - match:
        - port: 2222
      route:
        - destination:
            host: deadend.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 2222
