---
apiVersion: v2
name: harbor
description: Harbor registry and virtual services
type: application
version: 0.0.5
appVersion: "1.18.3"
dependencies:
  - name: harbor
    version: 1.18.3
    repository: https://helm.goharbor.io