---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jwks
    teknoir.org/plugin: jwks
  name: jwks
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jwks
  template:
    metadata:
      labels:
        app: jwks
      annotations:
        proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true }'
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: jwks
          image: "{{ .Values.jwks.image.registry }}:{{ .Values.jwks.image.version }}"
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8083"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8083
            initialDelaySeconds: 25
            periodSeconds: 20
          ports:
            - containerPort: 8083
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- if .Values.jwks.resources }}
          resources:
            {{- toYaml .Values.jwks.resources | nindent 12 }}
          {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
        - name: redis
          image: "{{ .Values.redis.image.registry }}:{{ .Values.redis.image.version }}"
          ports:
            - containerPort: 6379
          {{- if .Values.redis.resources }}
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: redis-persistent-storage
              mountPath: /data
      volumes:
        - name: redis-persistent-storage
          persistentVolumeClaim:
            claimName: jwks
