---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jwks
  namespace: {{ .Release.Namespace }}
  labels:
    app: jwks
    teknoir.org/plugin: jwks
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaimSize }}
