---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: mongodb-teknoir-system-allow
  namespace: {{ .Release.Namespace }}
  annotations:
    teknoir.org/plugin: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces:
              - "teknoir-system"
