{{- $username := ( include "mongodb.username" .) -}}
{{- $password := ( include "mongodb.password" .) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app: mongodb
    teknoir.org/plugin: mongodb
type: Opaque
data:
  username: {{ $username | b64enc | quote }}
  password: {{ $password | b64enc | quote }}
  service_uri: {{ printf "mongodb://%s:%s@mongodb.%s:27017/?authSource=admin" $username $password .Release.Namespace | b64enc | quote }}