---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-pgadmin-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: postgres
    teknoir.org/plugin: postgres
    purpose: data
    owner: teknoir
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "Local PostgreSQL",
          "Group": "Servers",
          "Host": "127.0.0.1",
          "Port": 5432,
          "MaintenanceDB": "postgres",
          "Username": "postgres",
          "SSLMode": "prefer",
          "PassFile": "/pgpassfile"
        }
      }
    }
