---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: postgres
    teknoir.org/plugin: postgres
    owner: teknoir
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
    - name: http-postgres-web
      port: 8080
      targetPort: pgadmin
      protocol: TCP
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: postgres
    owner: teknoir
