apiVersion: v2
name: profile-plugin-claims
description: HelmChart to deploy the default Claims and ClaimSets for user permissions to a Teknoir Cluster.
type: application
version: 0.0.86
appVersion: "1.0.0"
