---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb2-auth
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-5"
  labels:
    app.kubernetes.io/name: influxdb2
    app.kubernetes.io/instance: influxdb2
    teknoir.org/plugin: influxdb2
    owner: teknoir
type: Opaque
data:
  admin-token: {{ include "influxdb2.adminToken" . | b64enc }}
  admin-password: {{ include "influxdb2.adminPassword" . | b64enc }}
