---
apiVersion: v1
kind: Service
metadata:
  name: influxdb2
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: influxdb2
    app.kubernetes.io/instance: influxdb2
    teknoir.org/plugin: influxdb2
    owner: teknoir
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8086
  selector:
    app.kubernetes.io/name: influxdb2
    app.kubernetes.io/instance: influxdb2
