---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: influxdb2
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: influxdb2
    app.kubernetes.io/instance: influxdb2
    teknoir.org/plugin: influxdb2
    owner: teknoir
