---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: observatory-ws
  namespace: {{ .Release.Namespace }}
  labels:
    app: observatory-wss-mqtt
    teknoir.org/plugin: observatory
spec:
  action: ALLOW
  rules:
    - to:
      - operation:
          paths: ["/{{ .Release.Namespace }}/observatory-wss-mqtt"]
          ports: ["8080"]
  selector:
    matchLabels:
      app: observatory-wss-mqtt
