apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: observatory-wss-mqtt-auth-policy
  namespace: {{ .Release.Namespace }}
  labels:
    app: observatory-wss-mqtt
    teknoir.org/plugin: observatory
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals: ["cluster.local/ns/teknoir-system/sa/admin-service-account"]
    - to:
      - operation:
          methods: ["GET"]
          ports: ["8080"]
  selector:
    matchLabels:
      app: observatory-wss-mqtt
