domain: teknoir.cloud
domainPrefix:
persistentVolumeClaimSize: 100Gi
mongodb:
  image:
    registry: mongo
    version: 8.2.1
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
exporter:
  image:
    registry: docker.io/percona/mongodb_exporter
    version: 0.47
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
#mcpServerVersion: 1.2.0
