apiVersion: v2
name: monitoring
description: Prometheus and Grafana for cluster monitoring
type: application
version: 0.0.3
appVersion: "82.18.0"
dependencies:
  - name: kube-prometheus-stack
    version: 82.18.0
    repository: https://prometheus-community.github.io/helm-charts
