domain: teknoir.cloud
domainPrefix:

historianApiVersion: latest
historianMiddleendVersion: latest
historianStreamsVersion: latest
mongodbVersion: 8.2.1
exporterVersion: 0.47

imagePullSecrets:
  - name: ghcr-token

persistentVolumeClaimSize: 10Gi
streams:
  - stream: "sync-alerts"
  - stream: "sync-movements"
#  - stream: "alert-snapshots"
#  - stream: "movement-snapshots"