apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ .Values.labelSelectorKey }}: {{ .Values.labelSelectorValue }}
    teknoir.org/plugin: grafana
