---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: backstage-request-auth
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: backstage
  jwtRules:
    - issuer: "https://auth.{{ .Values.config.domain }}/auth/realms/master"
      jwksUri: "https://auth.{{ .Values.config.domain }}/auth/realms/master/protocol/openid-connect/certs"
      outputPayloadToHeader: verified-jwt
      fromHeaders:
        {{- range .Values.istio.jwt.fromHeaders }}
        - name: {{ .name }}
        {{- end }}

---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: backstage-api-request-auth
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: backstage-api
  jwtRules:
    - issuer: "https://auth.{{ .Values.config.domain }}/auth/realms/master"
      jwksUri: "https://auth.{{ .Values.config.domain }}/auth/realms/master/protocol/openid-connect/certs"
      outputPayloadToHeader: verified-jwt
      fromHeaders:
        {{- range .Values.istio.jwt.fromHeaders }}
        - name: {{ .name }}
        {{- end }}
