apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backstage-techdocs
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
