{{- if .Values.harbor.valuesContent.persistence.enabled }}
{{- $root := . }}
{{- range $name, $pvc := .Values.harbor.valuesContent.persistence.persistentVolumeClaim }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  {{- if $pvc.existingClaim }}
  name: {{ $pvc.existingClaim }}-pv
  {{- else }}
  name: harbor-{{ $name }}-pv
  {{- end }}
spec:
  capacity:
    storage: {{ $pvc.size }}
  accessModes:
    - {{ $pvc.accessMode | default "ReadWriteOnce" }}
  storageClassName: {{ $pvc.storageClass | default "" | quote }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ printf "%s/%s" $root.Values.harbor.valuesContent.persistence.hostPathPrefix $name | quote }}
    type: DirectoryOrCreate
{{- end }}
{{- end }}
