{{- $namespace := .Values.namespace | default .Release.Namespace -}}
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: harbor-core-mtls
  namespace: {{ $namespace }}
spec:
  # Apply this rule to all services in the harbor namespace
  host: "harbor-core.{{ $namespace }}.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: harbor-portal-mtls
  namespace: {{ $namespace }}
spec:
  # Apply this rule to all services in the harbor namespace
  host: "harbor-portal.{{ $namespace }}.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL