{{- if .Values.harbor.valuesContent.persistence.enabled }}
{{- $root := . }}
{{- $namespace := .Values.namespace | default .Release.Namespace -}}
{{- range $name, $pvc := .Values.harbor.valuesContent.persistence.persistentVolumeClaim }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- if $pvc.existingClaim }}
  name: {{ $pvc.existingClaim }}
  {{- else }}
  name: harbor-{{ $name }}-pvc
  {{- end }}
  namespace: {{ $namespace }}
spec:
  accessModes:
    - {{ $pvc.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ $pvc.size }}
  storageClassName: {{ $pvc.storageClass | default "" | quote }}
  {{- if $pvc.existingClaim }}
  volumeName: {{ $pvc.existingClaim }}-pv

  {{- else }}
  volumeName: harbor-{{ $name }}-pv
  {{- end }}
{{- end }}
{{- end }}
