---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: useralerts
  namespace: {{ .Release.Namespace }}
  labels:
    app: useralerts
    app.kubernetes.io/name: useralerts
    app.kubernetes.io/instance: useralerts
    teknoir.org/plugin: useralerts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: useralerts
  template:
    metadata:
      labels:
        app: useralerts
    spec:
      serviceAccountName: default-editor
      containers:
        - name: useralerts
          image: "{{ .Values.useralerts.image.registry }}:{{ .Values.useralerts.image.version }}"
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              value: {{ .Release.Namespace | quote }}
            - name: EMQX_URL
              value: "mqtt://emqx.{{ .Release.Namespace }}.svc.cluster.local:1883"
            - name: EMQX_USERNAME
              valueFrom:
                secretKeyRef:
                  name: emqx-bootstrap-user
                  key: username
            - name: EMQX_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: emqx-bootstrap-user
                  key: password
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
