---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: historian-mongodb
  namespace: {{ .Release.Namespace }}
  labels:
    app: historian-mongodb
    teknoir.org/plugin: historian
spec:
  serviceName: historian-mongodb
  replicas: 1
  selector:
    matchLabels:
      app: historian-mongodb
  template:
    metadata:
      labels:
        app: historian-mongodb
        teknoir.org/plugin: historian
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9216"
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.mongodb.image.registry }}:{{ .Values.mongodb.image.version }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: mongodb
              containerPort: 27017
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: mongodb
          readinessProbe:
            tcpSocket:
              port: mongodb
          startupProbe:
            tcpSocket:
              port: mongodb
          volumeMounts:
            - name: data
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: historian-mongodb-credentials
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: historian-mongodb-credentials
                  key: password
            - name: MONGO_INITDB_DATABASE
              value: "historian"
          {{- if .Values.mongodb.resources }}
          resources:
            {{- toYaml .Values.mongodb.resources | nindent 12 }}
          {{- end }}
        - name: mongodb-exporter
          image: "{{ .Values.exporter.image.registry }}:{{ .Values.exporter.image.version }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 9216
          args: ["--mongodb.uri=mongodb://$(MONGODB_USER):$(MONGODB_PASSWORD)@localhost:27017/admin", "--discovering-mode", "--collect-all", "--compatible-mode"]
          env:
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: historian-mongodb-credentials
                  key: username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: historian-mongodb-credentials
                  key: password
          {{- if .Values.exporter.resources }}
          resources:
            {{- toYaml .Values.exporter.resources | nindent 12 }}
          {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.persistentVolumeClaimSize }}
