# GitOps values for profile-controller.

replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/teknoir-mgmt/controllers/profile-controller
  tag: 20260408-151400
  pullPolicy: Always

imagePullSecrets:
  - name: gcr-json-key

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

serviceAccount:
  # Annotations to add to the service account
  annotations: {}


config:
  admin: "anders.aslund@teknoir.ai"
  workloadIdentity: ""
  userIdHeader: "X-Auth-Request-Email"
  userIdPrefix: ""
  projectId: "teknoir"
  domain: "teknoir.cloud"
  domainPrefix: ""
  region: "us-central1"
  dnsZone: "teknoir-cloud"
  istioRevision: "1.29.0"

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
