domain: teknoir.cloud
domainPrefix:

observatoryVersion: latest
wssMqttVersion: latest
snapshotExporterVersion: latest
mediaServiceVersion: latest
keydbVersion: x86_64_v6.3.4

imagePullSecrets:
  - name: ghcr-token

logLevel: info
inferenceTopic: "/devices/+/events/inference"
flushCacheBufferInterval: "30000"

pvcSize: 10Gi
serviceAccountName: default-editor
