domain: teknoir.cloud
domainPrefix:

observatoryVersion: main-39f7560
wssMqttVersion: dev-440733c
snapshotExporterVersion: dev-latest
mediaServiceVersion: latest
mediaPipelineVersion: dev-b2133d3
keydbVersion: x86_64_v6.3.4

logLevel: info
inferenceTopic: "/devices/+/events/inference"
flushCacheBufferInterval: "30000"

pvcSize: 10Gi
serviceAccountName: default-editor
