{{- $namespace := .Values.namespace | default .Release.Namespace -}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: teknoir
  name: custom-istio-component-monitor
  namespace: {{ $namespace }}
spec:
  endpoints:
    - interval: 15s
      port: http-monitoring
  jobLabel: istio
  namespaceSelector:
    any: true
  selector:
    matchExpressions:
      - key: istio
        operator: In
        values:
          - pilot
  targetLabels:
    - app

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: teknoir
  name: custom-prometheus-ns-monitor
  namespace: {{ $namespace }}
spec:
  endpoints:
    - interval: 15s
      port: http
  jobLabel: prometheus-external-search
  namespaceSelector:
    any: true
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - prometheus
  targetLabels:
    - app