---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notebook-controller
spec:
  destination:
    namespace: teknoir-system
    server: https://kubernetes.default.svc
  source:
    path: charts/notebook-controller
    repoURL: https://github.com/teknoir/profile-controller-helm
    targetRevision: {{ .Values.project }}
  sources: [ ]
  project: {{ .Values.project }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devstudio-controller
spec:
  destination:
    namespace: teknoir-system
    server: https://kubernetes.default.svc
  source:
    path: charts/devstudio-controller
    repoURL: https://github.com/teknoir/profile-controller-helm
    targetRevision: {{ .Values.project }}
  sources: [ ]
  project: {{ .Values.project }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-controller
spec:
  destination:
    namespace: teknoir-system
    server: https://kubernetes.default.svc
  source:
    path: charts/user-controller
    repoURL: https://github.com/teknoir/profile-controller-helm
    targetRevision: {{ .Values.project }}
  sources: [ ]
  project: {{ .Values.project }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: profile-controller
spec:
  destination:
    namespace: teknoir-system
    server: https://kubernetes.default.svc
  source:
    path: charts/profile-controller
    repoURL: https://github.com/teknoir/profile-controller-helm
    targetRevision: {{ .Values.project }}
  sources: [ ]
  project: {{ .Values.project }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: device-controller
spec:
  destination:
    namespace: teknoir-system
    server: https://kubernetes.default.svc
  source:
    path: charts/device-controller
    repoURL: https://github.com/teknoir/profile-controller-helm
    targetRevision: {{ .Values.project }}
  sources: [ ]
  project: {{ .Values.project }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
spec:
  destination:
    namespace: teknoir-system
    server: https://kubernetes.default.svc
  source:
    path: charts/backstage
    repoURL: https://github.com/teknoir/profile-controller-helm
    targetRevision: {{ .Values.project }}
  sources: [ ]
  project: {{ .Values.project }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
spec:
  destination:
    namespace: teknoir-system
    server: https://kubernetes.default.svc
  source:
    path: charts/monitoring
    repoURL: https://github.com/teknoir/profile-controller-helm
    targetRevision: {{ .Values.project }}
  sources: [ ]
  project: {{ .Values.project }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true