---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: fleet-metrics
    teknoir.org/plugin: fleet-metrics
  name: fleet-metrics
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaimSize }}
