---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: fleet-metrics
    teknoir.org/plugin: fleet-metrics
  name: fleet-metrics
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:      ['teknoir.org']
    resources:      ['devices']
    verbs:          ['list', 'get', 'watch', 'update', 'patch']
