domain: teknoir.cloud
domainPrefix:

emqx:
  replicaCount: 1
  persistence:
    enabled: true
    size: 1Gi
  apiKey: teknoir
  apiSecret: teknoir
  emqxConfig:
    EMQX_API_KEY__BOOTSTRAP_FILE: "/opt/emqx-bootstrap/api-keys.txt"
    EMQX_CLUSTER__DISCOVERY_STRATEGY: "k8s"
    EMQX_DASHBOARD__DEFAULT_USERNAME: "teknoir"
    EMQX_DASHBOARD__DEFAULT_PASSWORD: "teknoir"
    # --AUTHENTICATION & AUTHORIZATION ---
    # 1. Built-in Database Authentication
    EMQX_AUTHENTICATION__1__ENABLE: "true"
    EMQX_AUTHENTICATION__1__MECHANISM: "password_based"
    EMQX_AUTHENTICATION__1__BACKEND: "built_in_database"
    # 2. JWKS Authentication
    EMQX_AUTHENTICATION__2__ENABLE: "true"
    EMQX_AUTHENTICATION__2__MECHANISM: "jwt"
    EMQX_AUTHENTICATION__2__USE_JWKS: "true"
    EMQX_AUTHENTICATION__2__ENDPOINT: "http://jwks:8083/api/v1/keys"
    EMQX_AUTHENTICATION__2__FROM: "password"
    #refresh_interval = 60
    EMQX_AUTHENTICATION__2__REFRESH_INTERVAL: "60"
    #ssl = {enable = false}
    EMQX_AUTHENTICATION__2__SSL__ENABLE: "false"
    #acl_claim_name = "acl"
    EMQX_AUTHENTICATION__2__ACL_CLAIM_NAME: "acl"
    #verify_claims = {aud = "{{.projectId}}"}
    EMQX_AUTHENTICATION__2__VERIFY_CLAIMS: '{aud= \"teknoir\"}'
    EMQX_MAX_PACKET_SIZE: "3M"
    EMQX_LISTENER__SSL__KEYFILE: "/certs/tls.key"
    EMQX_LISTENER__SSL__CERTFILE: "/certs/tls.crt"
#    EMQX_LISTENER__SSL__EXTERNAL__KEYFILE: "/certs/tls.key"
#    EMQX_LISTENER__SSL__EXTERNAL__CERTFILE: "/certs/tls.crt"
#    EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__KEYFILE: "/certs/tls.key"
#    EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__CERTFILE: "/certs/tls.crt"
  pdb:
    enabled: false
    maxUnavailable: 1
  extraVolumeMounts:
    - name: emqx-bootstrap-api-keys
      mountPath: /opt/emqx-bootstrap
      readOnly: true
    - name: emqx-certs
      mountPath: /certs
      readOnly: true
  extraVolumes:
    - name: emqx-bootstrap-api-keys
      secret:
        secretName: emqx-bootstrap-api-keys
    - name: emqx-certs
      secret:
        secretName: domain-wildcard-tls